"""The model layers as recordable, non-fatal steps (GUIDE §6 rule 15).

Before 2026-08-24 the finalizer called analyze → plain → compose →
sections → tags bare, so one provider error anywhere was a traceback,
an exit 1, and — three attempts later — a halted day. Eight of ten
digests were regenerated by hand that fortnight. This module is the
seam the ruling required: every layer is attempted, its outcome is
recorded per day in `day_inference` (`fapd.inference`), and the caller
renders on whatever is stored. Validation is untouched — the §2 gates
still decide whether the render stands.

Two scripts share it (`scripts/run_pipeline.py`, `scripts/digest.py`)
so the finalizer and a manual re-render cannot drift in what "ran the
model layers" means. Deliberately not in `analyze.py`: that module is
the map layer, not the orchestration of all five.
"""

import logging

from . import inference
from .llm import LLMError, ProviderUnavailableError

logger = logging.getLogger("fapd.finalize")

#: Layer name -> the function that runs it, in the order the finalizer
#: has always used. Each takes (conn, llm_client, date) and returns its
#: stats dict. Imported lazily so a render-only process (digest.py's
#: ImportError path) never pays for the analysis modules.
LAYER_ORDER = inference.LAYERS  # ("map", "plain", "compose", "sections", "tags")


def _layer_fn(name):
    from . import analyze, compose, tags

    return {
        "map": analyze.run,
        "plain": analyze.run_plain,
        "compose": compose.compose_day,
        "sections": compose.compose_sections,
        "tags": tags.run,
    }[name]


def run_model_layers(conn, llm_client, date, *, record=True):
    """Attempt every model layer for `date`; never raise for a provider.

    Returns {"stats": {layer: stats-or-None}, "layers": {layer: outcome},
    "status": llm_client.status()} where outcome is "ran", "skipped"
    (the provider was already known unavailable, so the layer was not
    attempted — no call, no tokens), or "failed" (the layer raised an
    LLMError; whatever it stored before raising stays stored, rule 5).
    Anything that is not an LLMError propagates — a bug in our own code
    is still a bug, and the finalizer ladder is the right place for it.

    With record=True (the finalizer and digest.py) the outcome is
    written to day_inference, which is what the digest's Inference row
    reads. The published wording never carries the reason (operator
    ruling 2026-08-24); the reason is logged here and lands in the
    operations report.
    """
    stats = {}
    layers = {}
    for name in LAYER_ORDER:
        unavailable = llm_client.status().get("unavailable")
        if unavailable:
            layers[name] = "skipped"
            stats[name] = None
            continue
        try:
            stats[name] = _layer_fn(name)(conn, llm_client, date)
            layers[name] = "ran"
        except ProviderUnavailableError as exc:
            layers[name] = "failed"
            stats[name] = None
            logger.warning("%s: %s layer not available — %s (remaining layers"
                           " skipped; the day renders mechanically)",
                           date, name, exc.reason)
        except LLMError as exc:
            layers[name] = "failed"
            stats[name] = None
            logger.warning("%s: %s layer failed — %s (the day renders on what"
                           " is stored)", date, name, str(exc)[:300])
    status = llm_client.status()
    if record:
        inference.record(conn, date, backend=status.get("backend"),
                         models=status.get("models_used") or [],
                         layers=layers)
    return {"stats": stats, "layers": layers, "status": status}


def summary_line(result):
    """One log/console line for the layer outcomes — the operator-facing
    surface, so the reason is welcome here."""
    parts = [f"{name}={outcome}" for name, outcome in result["layers"].items()]
    unavailable = result["status"].get("unavailable")
    tail = f" — provider unavailable: {unavailable}" if unavailable else ""
    return "layers: " + " ".join(parts) + tail
